baseURL = 'https://taihen.org/'
languageCode = 'en-us'
title = 'taihen.org / 418 ... engineering in progress'
theme = 'ananke'
enableRobotsTXT = true

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 20
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 30
[[menu.main]]
  name = "Trainings"
  url = "/trainings/"
  weight = 40
[[menu.main]]
  name = "GitHub"
  url = "https://github.com/taihen"
  weight = 50
[[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 60


[pagination]
pagerSize = 9

[params]
text_color = ""
favicon = ""
site_logo = ""
background_color_class = "bg-black"
featured_image_class = "cover bg-top"
cover_dimming_class = "bg-black-60"
recent_posts_number = 6

[services]
  [services.googleAnalytics]
    id = 'G-36HC46PNZV'
